# --- vim uyumu ---
set -sg escape-time 10

# --- genel ---
set -g mouse on
set -g history-limit 10000

# --- yeni pane bulunulan dizinde acilsin ---
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# --- vim yonleriyle pane gecisi ---
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# --- prefix gostergesi ---
set -g status-left-length 20
set -g status-left '#{?client_prefix,#[reverse] PREFIX #[noreverse] ,}[#S] '
